name: build-and-push-image

on:
  push:
    branches:
      - main

env:
  LOCAL_REGISTRY: ghcr.io/parrot-com
  IMAGE_REPOSITORY: meilisearch-ui

jobs:
  Backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        id: build-image
        uses: docker/build-push-action@v2
        env:
          LOCAL_IMAGE_URL: ${{ env.LOCAL_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:latest
        with:
          file: Dockerfile
          tags: ${{ env.LOCAL_IMAGE_URL }}
          push: true
